name: Build test
on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'lib*/docs/**'

  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'Documentation/**'
      - 'lib*/docs/**'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: macos-latest
    env: 
        COMPILER: "clang"
        SANITIZE: "no"
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Configure
        run: .github/workflows/cibuild.sh CONFIGURE
      - name: Make
        run: .github/workflows/cibuild.sh MAKE
